# -*- coding: utf-8 -*-
"""Curated reading guides for the first batch of corpus classics."""

from __future__ import annotations


READING_GUIDES: dict[str, dict[str, object]] = {
    "KR1a0001": {
        "difficulty": "进阶",
        "guide_summary": "适合想理解中国古代思维方式的人，不必一开始就把它当占卜书。",
        "reading_tip": "先把它当成讲变化与判断的方法论来读，优先看乾、坤等基础卦，再慢慢进入完整体系。",
        "recommended_chapters": ["乾第一", "坤第二", "系辞上"],
    },
    "KR1b0001": {
        "difficulty": "进阶",
        "guide_summary": "适合想从上古政治语言和历史叙事里读出中国早期国家观念的人。",
        "reading_tip": "《尚书》篇幅跨度大，建议先读《尧典》《皋陶谟》这类相对常见篇章，再回头读诰命类文献。",
        "recommended_chapters": ["《尧典》", "《皋陶谟》", "《禹贡》"],
    },
    "KR1c0001": {
        "difficulty": "入门",
        "guide_summary": "如果你想先从有画面、有情感的古代文本开始，《诗经》会比很多经典更容易进入。",
        "reading_tip": "不要急着通读，先从熟悉的篇章开始，比如《关雎》《蒹葭》，先感受意象和节奏。",
        "recommended_chapters": ["周南", "秦风", "小雅"],
    },
    "KR1d0052": {
        "difficulty": "进阶",
        "guide_summary": "适合对古代礼制、修身观念和日常秩序感兴趣的人。",
        "reading_tip": "《礼记》章节很多，建议先读《大学》《中庸》《曲礼》，先抓住修身与礼的主线。",
        "recommended_chapters": ["大学", "中庸", "曲礼上"],
    },
    "KR1e0001": {
        "difficulty": "挑战",
        "guide_summary": "适合想把历史事件当成连续叙事来读的人，它能集中看到先秦政治与人物关系的展开。",
        "reading_tip": "不必一开始就通读全书，先从著名事件切入，比如“郑伯克段于鄢”“烛之武退秦师”。",
        "recommended_chapters": ["隐公元年", "僖公三十年", "襄公二十五年"],
    },
    "KR1f0001": {
        "difficulty": "入门",
        "guide_summary": "篇幅短，适合作为进入儒家伦理文本的第一本书。",
        "reading_tip": "它不长，适合一口气读完，再回过头看其中对亲情、政治和秩序的关系是怎么说的。",
        "recommended_chapters": ["开宗明义章", "三才章", "圣治章"],
    },
    "KR1h0004": {
        "difficulty": "入门",
        "guide_summary": "最适合第一次正式读古籍的人，句子短，主题清楚，也最容易与今天的生活对照。",
        "reading_tip": "不用从头硬读，先读《学而》《为政》《里仁》，先抓“学习、做人、待人”的主线。",
        "recommended_chapters": ["學而", "為政", "里仁", "顏淵"],
    },
    "KR1h0001": {
        "difficulty": "入门",
        "guide_summary": "如果你想读到论点更鲜明、辩论感更强的儒家文本，《孟子》会很适合。",
        "reading_tip": "先读《梁惠王上》《告子上》，这些篇章最容易看出孟子为什么总把“仁义”说得这么强。",
        "recommended_chapters": ["梁惠王上", "公孙丑上", "告子上"],
    },
    "KR1h0018": {
        "difficulty": "进阶",
        "guide_summary": "适合把《中庸》当作修身与处世原则来慢慢读的人，比直接通读全篇更容易进入。",
        "reading_tip": "先抓“中”“和”“诚”这几个核心词，不必急着把每一层义理一次吃透。",
        "recommended_chapters": ["卷一", "卷二", "卷三"],
    },
    "KR1h0029": {
        "difficulty": "进阶",
        "guide_summary": "如果你想把《大学》读成一条清晰的修身路径，这类疏义本会提供更明确的引导。",
        "reading_tip": "先抓“三纲领、八条目”这条主线，再回头看每一步为什么这样展开。",
        "recommended_chapters": ["卷一"],
    },
    "KR2a0001": {
        "difficulty": "进阶",
        "guide_summary": "它像一部规模很大的人物传记汇编，适合通过人物进入中国历史。",
        "reading_tip": "不要试图按卷全读，先挑《项羽本纪》《廉颇蔺相如列传》《刺客列传》这种叙事强的篇章。",
        "recommended_chapters": ["项羽本纪", "高祖本纪", "刺客列传"],
    },
    "KR2a0012": {
        "difficulty": "进阶",
        "guide_summary": "如果你想读三国人物而不是只看演义，《三国志》会是更可靠的入口。",
        "reading_tip": "先从熟悉人物切进去，比如曹操、诸葛亮、孙权，再慢慢体会正史的写法为什么更克制。",
        "recommended_chapters": ["魏书武帝纪", "蜀书诸葛亮传", "吴书孙权传"],
    },
    "KR2b0007": {
        "difficulty": "挑战",
        "guide_summary": "适合把历史当成长时段连续叙事来读的人，它提供了一条清晰的时间主线。",
        "reading_tip": "不要硬读全书，先从自己熟悉的朝代切进去，再借目录把前后事件串起来。",
        "recommended_chapters": ["周纪", "秦纪", "汉纪"],
    },
    "KR2e0001": {
        "difficulty": "进阶",
        "guide_summary": "它比《左传》更像各国历史与言论汇编，适合从人物发言和外交场景进入先秦史。",
        "reading_tip": "先从自己熟悉的国家切入，比如周语、晋语、楚语，再慢慢比较各国说话方式的不同。",
        "recommended_chapters": ["周語", "晉語", "楚語"],
    },
    "KR2e0003": {
        "difficulty": "进阶",
        "guide_summary": "如果你想读纵横家、说客和战国政治博弈，《战国策》会是很好的入口。",
        "reading_tip": "先从秦策、赵策、燕策这些名场面多的部分读起，更容易进入状态。",
        "recommended_chapters": ["秦策", "赵策", "燕策"],
    },
    "KR2e0006": {
        "difficulty": "入门",
        "guide_summary": "想看唐太宗怎样和群臣讨论治理国家，这本书会非常直观，也很适合答辩展示“经世致用”价值。",
        "reading_tip": "把它当成帝王与大臣的治理对话来读，先看纳谏、任贤、治国这些最容易懂的主题。",
        "recommended_chapters": ["君道", "政體", "納諫"],
    },
    "KR2g0003": {
        "difficulty": "入门",
        "guide_summary": "篇幅短、故事感强，适合从机智应对和政治劝谏故事进入先秦人物阅读。",
        "reading_tip": "先把它当君臣问答故事集来读，先抓晏子的说话方式，再回头看政治背景。",
        "recommended_chapters": ["卷第一", "卷第二", "卷第三"],
    },
    "KR3a0002": {
        "difficulty": "进阶",
        "guide_summary": "如果说《论语》更像谈做人，《荀子》则更像条分缕析地谈制度、学习与人性。",
        "reading_tip": "先读《劝学》《性恶》《修身》，先抓住荀子最鲜明的几条主张。",
        "recommended_chapters": ["勸學", "性惡", "修身"],
    },
    "KR3a0006": {
        "difficulty": "进阶",
        "guide_summary": "它像一场朝廷大辩论，特别适合展示“古籍与现实问题”的连接能力。",
        "reading_tip": "先把它当政策辩论现场来读，抓住朝廷到底在争什么，不必先陷进术语。",
        "recommended_chapters": ["本議", "力耕", "復古"],
    },
    "KR3a0042": {
        "difficulty": "进阶",
        "guide_summary": "这是理学入门的代表选本，适合从较短片段理解宋儒如何整理修身与治学。",
        "reading_tip": "不要连续硬读，先挑主题词，比如“敬”“诚”“学”，按主题看会更容易进入。",
        "recommended_chapters": ["卷一", "卷二", "卷三"],
    },
    "KR3a0058": {
        "difficulty": "进阶",
        "guide_summary": "它把《大学》的修身框架一路推到治国层面，适合比赛里强调“古籍与现实治理”的连接。",
        "reading_tip": "先把它当成“从个人修养走向公共治理”的延展阅读，不必追求一次通读全书。",
        "recommended_chapters": ["卷一", "卷二", "卷三"],
    },
    "KR3b0003": {
        "difficulty": "入门",
        "guide_summary": "篇幅短、结构清楚，非常适合作为兵家文本的第一本入门书。",
        "reading_tip": "先抓“谋”“势”“变”这三条主线，不要只把它当打仗技巧书。",
        "recommended_chapters": ["始計", "謀攻", "兵勢"],
    },
    "KR3c0001": {
        "difficulty": "进阶",
        "guide_summary": "它是先秦政治与经济思想的大杂烩，适合从现实治理问题进入古籍阅读。",
        "reading_tip": "先找自己熟悉的主题读，比如治国、法度、富国，再慢慢感受这部书的杂糅性。",
        "recommended_chapters": ["牧民", "權修", "立政"],
    },
    "KR3c0005": {
        "difficulty": "进阶",
        "guide_summary": "适合想看先秦政治现实主义的人，语气锋利，观点也更直接。",
        "reading_tip": "先读《五蠹》《说难》《喻老》，先看韩非到底在批评谁、想解决什么问题。",
        "recommended_chapters": ["五蠹", "說難", "喻老"],
    },
    "KR3j0002": {
        "difficulty": "进阶",
        "guide_summary": "如果你想看和儒家很不一样的价值立场，《墨子》会给人很强的对照感。",
        "reading_tip": "先读《兼爱》《非攻》《尚贤》，先抓墨家到底在反对什么、主张什么。",
        "recommended_chapters": ["兼愛", "非攻", "尚賢"],
    },
    "KR3j0009": {
        "difficulty": "进阶",
        "guide_summary": "它像一部杂家思想总汇，适合想比较不同先秦观点的人。",
        "reading_tip": "先挑议论性强、故事也好懂的篇章读，比如《察今》这类常被引用的段落。",
        "recommended_chapters": ["察今", "貴公", "勸學"],
    },
    "KR3j0092": {
        "difficulty": "入门",
        "guide_summary": "它像宋代学者的观察手记，适合从具体条目进入古人的思考方式。",
        "reading_tip": "先把它当博物与技术随笔来读，遇到感兴趣的条目就顺着追，不必追求整齐通读。",
        "recommended_chapters": ["卷一", "卷二", "卷三"],
    },
    "KR3l0002": {
        "difficulty": "入门",
        "guide_summary": "短则一则、长则一页，非常适合碎片化阅读，也是理解魏晋人物风度的好入口。",
        "reading_tip": "先把它当人物逸事集来读，不必一开始就追求体系，读到有趣的人物再回头查背景。",
        "recommended_chapters": ["德行", "言语", "任诞"],
    },
    "KR3l0090": {
        "difficulty": "入门",
        "guide_summary": "它很适合从异兽、地理和神话意象进入，也是理解上古想象力的重要入口。",
        "reading_tip": "可以先把它当作神话与地理并置的文本来读，读到熟悉的异兽和山川，再慢慢追索背后的文化含义。",
        "recommended_chapters": ["南山經", "西山經", "海外南經"],
    },
    "KR3l0099": {
        "difficulty": "入门",
        "guide_summary": "如果你喜欢志怪故事和民间想象，《搜神记》会比很多正统经典更容易上手。",
        "reading_tip": "先读短篇故事，不必求全懂，先把人物、异象和故事张力抓住。",
        "recommended_chapters": ["卷一", "卷二", "卷三"],
    },
    "KR4a0001": {
        "difficulty": "进阶",
        "guide_summary": "适合想读更浓烈情感、更强抒情性的古典作品的人。",
        "reading_tip": "先读《离骚》《九歌》，先感受屈原式的情感表达，再慢慢进入更复杂的篇章。",
        "recommended_chapters": ["離騷", "九歌", "天問"],
    },
    "KR4h0001": {
        "difficulty": "进阶",
        "guide_summary": "它像一部中国古代文学作品选集，适合从名篇切入而不是从头通读。",
        "reading_tip": "先挑熟悉作者的篇章，比如曹植、陶渊明、谢灵运，再顺着文体去比较差异。",
        "recommended_chapters": ["卷一", "卷二", "卷三"],
    },
    "KR4i0001": {
        "difficulty": "进阶",
        "guide_summary": "适合想知道古人怎样谈写作、文体和审美的人，它像中国古代文学理论总论。",
        "reading_tip": "先读《原道》《神思》《知音》，先抓住“文章从哪里来、怎样写、怎样评”的主线。",
        "recommended_chapters": ["原道", "神思", "知音"],
    },
    "KR5c0045": {
        "difficulty": "入门",
        "guide_summary": "篇幅短，但句意含蓄，适合慢读，不适合一口气求全懂。",
        "reading_tip": "先读前十章，重点抓“道、名、无为、欲望”这些核心词，不必急着把每句都解释死。",
        "recommended_chapters": ["體道章第一", "養身章第二", "虛用章第五"],
    },
    "KR5c0124": {
        "difficulty": "入门",
        "guide_summary": "比《庄子》更短，也更接近寓言故事集，适合从相对容易进入的道家文本开始读。",
        "reading_tip": "先把它当思想故事来读，先看故事里在质疑什么，再回头看道家立场。",
        "recommended_chapters": ["天瑞", "黃帝", "湯問"],
    },
    "KR5c0126": {
        "difficulty": "进阶",
        "guide_summary": "想读更自由、更跳脱的思想文本时，《庄子》会是很合适的选择。",
        "reading_tip": "先从《逍遥游》《齐物论》进入，不必先追求整齐的概念体系，先读出视角的变化感。",
        "recommended_chapters": ["內篇逍遙遊第一", "齊物論第一", "養生主第一"],
    },
    "KR6c0023": {
        "difficulty": "入门",
        "guide_summary": "篇幅不长，却很适合作为理解佛教“空”与“执著”问题的入口。",
        "reading_tip": "第一次读不要急着追求术语全懂，先抓“无住”“离相”这些核心表达。",
        "recommended_chapters": ["金剛般若波羅蜜經"],
    },
    "KR6c0128": {
        "difficulty": "入门",
        "guide_summary": "短小但高度浓缩，非常适合做佛学文本的第一本入门。",
        "reading_tip": "先抓“色即是空，空即是色”这条主线，不必一开始把每个术语都讲得过满。",
        "recommended_chapters": ["般若波羅蜜多心經"],
    },
    "KR6q0083": {
        "difficulty": "进阶",
        "guide_summary": "适合想读禅宗文本的人，它比一般经文更接近师徒问答体。",
        "reading_tip": "先读六祖身世与开悟相关部分，再看后面的问答公案，更容易进入禅宗语感。",
        "recommended_chapters": ["行由品", "般若品", "機緣品"],
    },
}
